version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
    - echo ///// $DEPLOY_ENV //////
    - echo Installing Serverless
    - npm install -g serverless
  pre_build:
    commands:
    - echo Installing source NPM dependencies...
    - npm install
    - npm audit fix
  build:
    commands:
    - echo Running Tests
    - npm run test-ci
  post_build:
    commands:
    - echo Deploy started on `date`
    - npm run deploy:$DEPLOY_ENV
    - echo 'fin'
    - echo Build completed on `date`
